name: Build
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'      

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache dist folder
        id: cache-dist
        uses: actions/cache@v3
        env:
          cache-name: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pnpm-lock.yaml') }}
          
      - name: Run build
        if: steps.cache-dist.outputs.cache-hit != 'true'
        run: pnpm build

        
      - name: Upload dist artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: dist
          path: dist