---
name: Workshop

on:
  push:
    branches:
      - main
      - paul
  pull_request: {}

env: 
  feedback: "Thank you. Great Workshop!"

jobs:
  echo:
    name: "echo"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: echo Hello World
        run: echo "Hello World"

      - name: feedback
        run: echo $feedback
  
  create-artifact: 
    name: "Create Artifact"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Artifact File
        run: echo $feedback >> artifact.txt
      
      - name: store artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact.txt

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'amazoncoretto'
      - run: cd backend
      - name: Maven-Build
        run: mvn package
      - name: store jar file
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: target/actions-workshop-backend.jar