name: Workshop
on:
  push:
    branches:
      - main
  pull_request: {} 

env:
  GREETING: Hello

jobs:
  print-greeting:
    name: Print greeting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print
        run: echo $GREETING

  save-greeting:
    name: Save greeting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Save to file
        run: echo $GREETING > greeting.txt
      
      - name: Store artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: greetingfile
          path: greeting.txt